#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ProteinHelper.Resource", IsApplication=true)]

namespace ProteinHelper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::ProteinHelper.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ProteinHelper.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ProteinHelper.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ProteinHelper.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_custom = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_high = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_highest = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_low = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_lowest = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_medhigh = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_medlow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_myInventory = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_refresh = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_save = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_scan = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_search = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_searchButton = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int proteinTracker_logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int SplashScreen = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08002e
			public const int addCustom = 2131230766;
			
			// aapt resource value: 0x7f080000
			public const int brandTxtView = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int brndNameEditTxt = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int calEditTxt = 2131230730;
			
			// aapt resource value: 0x7f08001c
			public const int calSearchImg = 2131230748;
			
			// aapt resource value: 0x7f08001f
			public const int calToggleBtn = 2131230751;
			
			// aapt resource value: 0x7f080012
			public const int calTxt = 2131230738;
			
			// aapt resource value: 0x7f080007
			public const int calTxtView = 2131230727;
			
			// aapt resource value: 0x7f080029
			public const int contentFrame = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int delete = 2131230762;
			
			// aapt resource value: 0x7f08000d
			public const int empty = 2131230733;
			
			// aapt resource value: 0x7f080021
			public const int frstNameTxtView = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int frstNmEditTxt = 2131230755;
			
			// aapt resource value: 0x7f08000c
			public const int inventoryListView = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout1 = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int linearLayout2 = 2131230731;
			
			// aapt resource value: 0x7f080024
			public const int lstNmEditTxt = 2131230756;
			
			// aapt resource value: 0x7f080022
			public const int lstNmTxtView = 2131230754;
			
			// aapt resource value: 0x7f08001e
			public const int maxCalQueryTxt = 2131230750;
			
			// aapt resource value: 0x7f08001a
			public const int maxPrtnQueryTxt = 2131230746;
			
			// aapt resource value: 0x7f08001d
			public const int minCalQueryTxt = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int minPrtnQueryTxt = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int myInventoryButton = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int myInventoryTxt = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int nameTxt = 2131230737;
			
			// aapt resource value: 0x7f080003
			public const int prdNameEditTxt = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int prdNameTxtView = 2131230722;
			
			// aapt resource value: 0x7f08000f
			public const int proteinTxt = 2131230735;
			
			// aapt resource value: 0x7f080009
			public const int prtnEditTxt = 2131230729;
			
			// aapt resource value: 0x7f080027
			public const int prtnGoalTxtView = 2131230759;
			
			// aapt resource value: 0x7f080013
			public const int prtnIndicator = 2131230739;
			
			// aapt resource value: 0x7f080028
			public const int prtnPicker = 2131230760;
			
			// aapt resource value: 0x7f080018
			public const int prtnSeachImg = 2131230744;
			
			// aapt resource value: 0x7f08001b
			public const int prtnToggleBtn = 2131230747;
			
			// aapt resource value: 0x7f080006
			public const int prtnTxtView = 2131230726;
			
			// aapt resource value: 0x7f080020
			public const int queryListView = 2131230752;
			
			// aapt resource value: 0x7f08002d
			public const int refresh = 2131230765;
			
			// aapt resource value: 0x7f08000e
			public const int relativeLayout1 = 2131230734;
			
			// aapt resource value: 0x7f08002b
			public const int save = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int scan = 2131230764;
			
			// aapt resource value: 0x7f080014
			public const int searchButton = 2131230740;
			
			// aapt resource value: 0x7f080016
			public const int searchTxt = 2131230742;
			
			// aapt resource value: 0x7f080004
			public const int tableLayout1 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int tableRow1 = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int tableRow2 = 2131230728;
			
			// aapt resource value: 0x7f080026
			public const int weightPicker = 2131230758;
			
			// aapt resource value: 0x7f080025
			public const int wghtGoalTxtView = 2131230757;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int FoodItemDetail = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Inventory = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int InventoryItem = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Query = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Settings = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int zxingscanneractivitylayout = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int zxingscannerfragmentlayout = 2130968583;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int FoodItemDetailMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int InventoryListViewMenu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int proteinTracker_logo = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
